[book]
title = "IETF 126 TEEP Wasm Demo"
authors = ["ZENBA Kazuki"]
language = "en"
src = "doc"

[output.html]
git-repository-url = "https://github.com/s-miyazawa/teep-wasm-demo"
git-repository-icon = "fab-github"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
