#
# Copyright (c) 2026 SECOM CO., LTD. All Rights reserved.
#
# SPDX-License-Identifier: BSD-2-Clause
#

services:
  container_tam:
    build: ./AttesTAM
    environment:
      - ATTESTAM_CHALLENGE_SERVER=https://host.docker.internal:8443
      - ATTESTAM_INSECURE_DEMO_MODE=true
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - tam-attester-net

  container_attester:
    build: ./taws
    environment:
      - TAWS_TAM_URL=http://container_tam:8080/tam
    ports:
      - "8181:8181"
    depends_on:
      - container_tam
    networks:
      - tam-attester-net


networks:
  tam-attester-net:
    driver: bridge
