#
# Copyright (c) 2025 SECOM CO., LTD. All Rights reserved.
#
# SPDX-License-Identifier: BSD-2-Clause
#

.PHONY: all
all:
	$(MAKE) -C psa
	$(MAKE) -C eat_evidence
	$(MAKE) -C corim

.PHONY: clean
clean:
	$(MAKE) -C psa clean
	$(MAKE) -C eat_evidence clean
	$(MAKE) -C corim clean

