#
# Copyright (c) 2025 SECOM CO., LTD. All Rights reserved.
#
# SPDX-License-Identifier: BSD-2-Clause
#

.PHONY: all
all:
	$(MAKE) -C ./text0
	$(MAKE) -C ./text1

.PHONY: install
install:
	$(MAKE) -C ./text0 install
	$(MAKE) -C ./text1 install

.PHONY: clean
clean:
	$(MAKE) -C ./text0 clean
	$(MAKE) -C ./text1 clean

