@startuml demo-usecase-operation
left to right direction
skinparam actorStyle awesome
title Demo Usecase

actor "Building Owner" as A_DeviceUser
actor "Security Service Provider" as A_ServiceProvider

rectangle "Demo System" as G_System {
  package "Device Functions" {
    usecase "Activate Device" as U_DeviceActivate
    usecase "Update Anomaly Detection Model" as U_CheckUpdate
    usecase "Use Anomaly Detection Model" as U_DeviceUse
  }
  package "TAM Functions" {
    usecase "Register TC to TAM" as U_TCRegister
    usecase "Distribute TC to Device" as U_TCInstall
    usecase "List Managed Devices" as U_ListDevices
    usecase "List Managed TCs" as U_ListTCs
    usecase "Verify Device" as U_DeviceAttest
  }
}

A_DeviceUser --  U_DeviceActivate
A_DeviceUser --  U_CheckUpdate
A_DeviceUser --  U_DeviceUse
U_DeviceActivate ..> U_TCInstall : <<include>>
U_CheckUpdate ..> U_TCInstall : <<include>>
U_TCInstall ..> U_DeviceAttest : <<include>>
A_ServiceProvider -up- U_TCRegister
A_ServiceProvider -up- U_ListDevices
A_ServiceProvider -up- U_ListTCs

@enduml
